/** Shared shapes for the GPX parity check. */

/** One case from `engine/jvm-routes.json`, generated by `./gradlew jvmRoutes`. */
export interface ReferenceRoute {
  id: string
  profile: string
  /** BRouter's URL waypoint format: `lon,lat|lon,lat|…` in degrees. */
  lonLats: string
  note: string
  ok: boolean
  gpxLength: number
  gpxCrc32: number
  jvmMs: number
  /** Tiles this route needs. Absent on older reference files. */
  tiles?: string[]
}

export interface JvmRoutes {
  generatedBy: string
  profileDir: string
  segmentDir: string
  routes: ReferenceRoute[]
}

export interface RouteResult extends ReferenceRoute {
  wasmMs: number
  error?: string
  actualCrc32?: number
  actualLength?: number
  /** True only when GPX byte length *and* CRC-32 both agree with the JVM. */
  matches?: boolean
}
