/** The two TeaVM backends emitted from the same Java source. */
export type BackendId = 'wasm-gc' | 'js'

export type KernelKind = 'distanceBits' | 'heapBenchmark' | 'crcBenchmark'

/**
 * Case definitions come from `engine/jvm-reference.json`, generated by
 * `./gradlew jvmParity`. The browser reads the corpus rather than restating it,
 * so there is only ever one copy of the test cases.
 */
export interface ReferenceCase {
  id: string
  kind: KernelKind
  args: number[]
  /** JVM result as a string: hex of the IEEE-754 bits for doubles, decimal for ints. */
  expected: string
  note: string
}

export interface ReferenceBenchmark {
  id: string
  kind: Exclude<KernelKind, 'distanceBits'>
  args: number[]
  iterations: number
  jvmBestMs: number
}

export interface JvmReference {
  generatedBy: string
  cases: ReferenceCase[]
  benchmarks: ReferenceBenchmark[]
}

export interface CaseResult {
  id: string
  note: string
  expected: string
  actual: string
  pass: boolean
}

export interface BenchResult {
  id: string
  jvmBestMs: number
  backendBestMs: number
  /** >1 means the browser backend is slower than the JVM. */
  slowdown: number
}

export interface BackendReport {
  backend: BackendId
  ok: boolean
  error?: string
  /** Time to fetch, compile and instantiate the module. */
  loadMs: number
  cases: CaseResult[]
  benchmarks: BenchResult[]
}

export interface SpikeRequest {
  backend: BackendId
  reference: JvmReference
  /**
   * The app's base URI, passed in from the main thread. The worker cannot derive
   * it: after bundling, `self.location` points at `/assets/engine.worker-<hash>.js`,
   * so resolving engine URLs relative to the worker lands in the wrong directory.
   */
  baseUrl: string
}
