import { describe, expect, it } from 'vitest'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { BIKES, SHOTS, SLIDES, bikeById } from './slides'
import { PROFILES } from '../ride/profiles'
import { POSITIONS, TYRES } from '../ride/rider'

const shotFile = (name: string) =>
  fileURLToPath(new URL(`../../public/onboarding/${name}.webp`, import.meta.url))

describe('the walkthrough', () => {
  it('ends on the location card, because it is the only one that asks for something', () => {
    expect(SLIDES[SLIDES.length - 1].location).toBe(true)
    expect(SLIDES.filter((s) => s.location)).toHaveLength(1)
  })

  it('asks about the bike exactly once', () => {
    expect(SLIDES.filter((s) => s.bikes)).toHaveLength(1)
  })

  it('shows a different screen on every card', () => {
    expect(new Set(SLIDES.map((s) => s.shot)).size).toBe(SLIDES.length)
  })
})

describe('the bike question', () => {
  /*
   * Every one of these three lands somewhere real. A renamed profile or a withdrawn tyre id
   * would otherwise write a setting the rest of the app silently falls back out of, and the
   * rider would never know the answer they gave had been discarded.
   */
  it('maps every bike onto a profile, a position and a tyre that exist', () => {
    for (const bike of BIKES) {
      expect(PROFILES.map((p) => p.id)).toContain(bike.profile)
      expect(POSITIONS.map((p) => p.id)).toContain(bike.position)
      expect(TYRES.map((t) => t.id)).toContain(bike.tyres)
    }
  })

  /*
   * The three cards are a fixed vocabulary — Relaxed, Fast, Off-road. A bike that suggested a
   * profile outside them would put a fourth name into the trio for one answer.
   */
  it('only ever suggests one of the three offered styles', () => {
    const offered = PROFILES.slice(0, 3).map((p) => p.id)
    for (const bike of BIKES) expect(offered).toContain(bike.profile)
  })

  it('falls back rather than throwing on an id that is no longer offered', () => {
    expect(bikeById('penny-farthing')).toBe(BIKES[0])
  })
})

describe('the pictures', () => {
  /*
   * The one failure a screenshot has that a drawing does not: the file is not there.
   *
   * These are generated by `tools/onboarding-shots.mjs` from a basemap, a routing segment and a
   * picker archive that are all far too large to commit, so nobody regenerating them in a fresh
   * checkout can be sure they all landed. A card whose picture 404s is a hole in the first thing
   * a rider ever sees, and nothing else in the build would say a word about it.
   */
  it('has a file on disk for every name a card asks for', () => {
    for (const slide of SLIDES) {
      expect(existsSync(shotFile(slide.shot)), `${slide.shot}.webp is missing`).toBe(true)
    }
  })

  it('declares every picture it ships, so an orphan is a failure rather than dead weight', () => {
    expect([...SHOTS].sort()).toEqual([...new Set(SLIDES.map((s) => s.shot))].sort())
  })

  /* A picture that repeats its caption is no better than the glyph it replaced; one that says
     nothing at all is worse, because a rider using VoiceOver gets six unlabelled images. */
  it('describes every picture in words that are not the title', () => {
    for (const slide of SLIDES) {
      expect(slide.alt.length, `${slide.shot} has no alt text`).toBeGreaterThan(30)
      expect(slide.alt).not.toBe(slide.title)
    }
  })
})
